### ISSUE TITLE
[BUG] Situation doesn't allow change of situation

### ISSUE THREAD

**Issue by schlosrat** [natalia-simonova/StageInfo#2]
Great mod! Very helpful, but for me there seems to be a bug in the latest release (0.4.).

When in the VAB with a vessel loaded, I bring up the engineers report which brings up Stage Info. The Situation shows stage 01 as Kerbin (ASL), and stage 02 as Kerbin. If I click on the situation, the interface you show in the video on SpaceDock pops up momentarily, but then instantly vanishes. It does not allow picking some other situation, and so I'm stuck with Kerbin when I'd like to see how my lander would do on Tylo.

This occurs with Space Warp 0.3.2 and the following other mods loaded
cheat_menu 0.2.1
ABrits_Transfer_calcularot-0.1.2 (ITCalculator)
LazyOrbit 0.3.0
maneuver_node_controller 0.03
micro_engineer 0.4.1
sticky_orbit_markers 0.2.1

**Comment by schlosrat** [comment]
I've also checked with with only this mod loaded and the same bug is there, so I don't think it's an interaction with another mod.

**Comment by natalia-simonova** [comment]
do you have any other vessels in flight? if so, try recovering them, save, quit and reload the game. it sounds like the known vessel bug

**Comment by natalia-simonova** [comment]
also, you can try using the clear button (top left) to empty the cache. if it instantly refills in the VAB, thats definitely the known vessel bug

**Comment by natalia-simonova** [comment]
the other potential source of the issue is exiting to main menu, if you did this beforehand, as this destroys a lot of game objects (including the base game's logger). a workaround is being used in the mod loader but its quite a bad stock issue that will hopefully be fixed soon

as all the sources of the problem are stock problems the issue has been closed
